# Site settings
title: The JS Ninja
email: ninja@onmylemon.co.uk
description: > # this means to ignore newlines until "baseurl:"
    Ninja your way through javascript
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thejs.ninja" # the base hostname & protocol for your site
twitter_username: lgoldstien
github_username: lgoldstien

# Build settings
markdown: kramdown
